---
title: "TAYSR_analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lme4)
```

## Individual-level growth response

```{r}
d20 <- 
  read.csv("TAYSR_2020_ALL.csv")
d20$COMP <- factor(d20$COMP)
d20$COMPGAP <- factor(d20$COMPGAP)
d20$TRT <- factor(d20$TRT)
d20$SPP <- factor(d20$SPP)
d20$P.NP <- factor(d20$P.NP)
d20$REPL <- factor(d20$REPL)

treatments <- data.frame(TRT = c("M", "MH", "MBB", "BB"), 
                         Treatment = c("Mastication only", 
                                       "Mastication + herbicide", 
                                       "Mastication + burn", 
                                       "Burn only" ))

d20 <- left_join(d20, treatments)
d20$scPDIF <- scale(d20$PER_DIFF)

d20
```




```{r}
d20_lm <- lm(scPDIF ~ TRT*SPP + REPL, data = d20)

op <- par(mfrow = c(2, 2), mar = c(4, 4, 2, 2))
plot(d20_lm, which = c(1))
plot(d20$TRT, resid(d20_lm), xlab = "TRT", ylab = "Residuals")
plot(d20$SPP, resid(d20_lm), xlab = "SPP", ylab = "Residuals")
plot(d20$COMPGAP, resid(d20_lm), xlab = "COMPGAP", ylab = "Residuals")
par(op)

ggplot() + geom_histogram(aes(x = resid(d20_lm)))

#don't know if there's much to gain from this figure since they're all categorical variables
Z <- cbind(d20$PER_DIFF, d20$TRT, d20$SPP, d20$COMPGAP)
colnames(Z) <- c("PER_DIFF", "TRT", "SPP", "COMPGAP")
#pairs(Z, lower.panel = panel.smooth, upper.panel = panel.cor, diag.panel = panel.hist)


shapiro.test(residuals(d20_lm))
car::leveneTest(PER_DIFF ~ TRT, data = d20)
summary(d20_lm)
```

```{r}
d20_cln <- d20[-c(358, 329, 248, 213, 172, 92, 5, 2, 401, 424, 374, 87, 96, 253, 194),]
d20_cln_lm <- lm(PER_DIFF ~ TRT*SPP + COMPGAP, data = d20_cln)

op <- par(mfrow = c(2, 2), mar = c(4, 4, 2, 2))
plot(fitted(d20_cln_lm), rstandard(d20_cln_lm), xlab = "Fitted values", ylab = "Standardized residuals")
plot(d20_cln$TRT, rstandard(d20_cln_lm), xlab = "TRT", ylab = "Standardized residuals")
plot(d20_cln$SPP, rstandard(d20_cln_lm), xlab = "SPP", ylab = "Standardized residuals")
plot(d20_cln$COMPGAP, rstandard(d20_cln_lm), xlab = "COMPGAP", ylab = "Standardized residuals")
par(op)

ggplot() + geom_histogram(aes(x = rstandard(d20_cln_lm)))

op <- par(mfrow = c(2, 2), mar = c(4, 4, 2, 2))
plot(d20_cln_lm)
par(op)


shapiro.test(residuals(d20_cln_lm))
car::leveneTest(PER_DIFF ~ TRT, data = d20_cln)

summary(d20_cln_lm)
drop1(d20_cln_lm, test = "F")
anova(d20_cln_lm)

```

```{r}
rstatix::identify_outliers(group_by(d20, TRT, SPP), variable = 'PER_DIFF')
```


```{r}
d20_cln_aov <- aov(scPDIF ~ TRT*SPP + REPL, data = d20_cln)
summary(d20_cln_aov)
d20_cln_Tuk <- TukeyHSD(d20_cln_aov)
plot(d20_cln_Tuk)
```

```{r}
d20_noGS <- d20_cln %>% 
  filter(SPP != 'GS')
```


```{r}
d20_TRT_mean <- d20_noGS %>% 
  group_by(Treatment) %>% 
  summarise(mean = mean(PER_DIFF))


d20_TRTSPP_mean <- d20_noGS %>% 
  group_by(Treatment, SPP) %>% 
  summarise(mean = mean(PER_DIFF))
d20_TRTSPP_mean$Species <- d20_TRTSPP_mean$SPP

ggplot() + 
  geom_boxplot(data = d20_noGS, aes(x = reorder(Treatment, -PER_DIFF, FUN = median), y = PER_DIFF), outlier.fill = NULL) + 
  #geom_point(data = d20_TRT_mean, aes(x = Treatment, y = mean), col = "red", pch = 3, size = 2) + 
  labs(x = "Treatment", 
       y = "Percent difference [%]") + 
  geom_line(data = d20_TRTSPP_mean, aes(x = Treatment, y = mean, group = Species, colour = Species)) + 
  geom_point(data = d20_TRTSPP_mean, aes(x = Treatment, y = mean, colour = Species), size = 0.8)
```

```{r}
d20_SPP_mean <- d20_noGS %>% 
  group_by(SPP) %>% 
  summarise(mean = mean(PER_DIFF))
d20_SPP_mean$Species <- d20_SPP_mean$SPP

d20_noGS$Species <- d20_noGS$SPP

ggplot(d20_noGS) + 
  geom_boxplot(aes(x = reorder(Species, PER_DIFF, FUN = median), y = PER_DIFF, fill = Species)) + 
  geom_point(data = d20_SPP_mean, aes(x = Species, y = mean), col = "red", pch = 4, size = 2) + 
  labs(x = "Species", 
       y = "Percent difference [%]") + 
  theme(legend.position = "none")
```

```{r}
ggplot() + 
  geom_boxplot(data = d20_noGS, aes(reorder(Treatment, -PER_DIFF, FUN = median), y = PER_DIFF)) + 
  geom_point(data = d20_TRT_mean, aes(x = Treatment, y = mean), col = "red", pch = 4, size = 2) + 
  labs(x = "Treatment", 
       y = "Percent difference [%]")
```

```{r}
DB_mean <- d20_cln %>% 
  group_by(TRT, P.NP) %>% 
  summarise(DB = mean(DEAD_BRANCHES))

ggplot(d20_cln) + 
  geom_boxplot(aes(x = TRT, y = DEAD_BRANCHES, col = P.NP))
```



```{r}
# d18 <- read.csv('TAYSR_2018_ALL.csv')
# d18$CGT <- paste(d18$COMPGAP, d18$TREE., sep = "")
# 
# d13 <- read.csv('TAYSR_2013_ALL.csv')
# d13$CGT <- paste(d13$COMPGAP, d13$TREE., sep = "")
# 
# d20$CGT <- paste(d20$COMPGAP, d20$TREE., sep = "")
# 
# d.all <- left_join(x = d20, y = d18, by = c('CGT' = 'CGT')) %>% 
#   left_join(y = d13, by = c('CGT' = 'CGT')) %>% 
#   rename(c("DBH_20" = "DBH_IN", "DBH_18" = "DBH.x", "DBH_13" = "DBH.y"))
# d.all
# 
# write_excel_csv(d.all, path = "C:/Users/Rob/Desktop/d.all.csv")
```

## Stand-level growth response

```{r}
d13 <- read.csv('TAYSR_2013_ALL.csv')
d18 <- read.csv('TAYSR_2018_ALL.csv')
plotsize_13_18 <- read.csv('plotsize_13_18.csv')
```

```{r}
dBA13 <- 
  d13 %>% 
  mutate(BA = (pi*(DBH/24)^2)) %>%
  group_by(TRT, COMPGAP) %>% 
  summarise(sumBA = sum(BA)) %>% 
  left_join(plotsize_13_18) %>% 
  mutate(BA13_AC = sumBA/SIZE13_AC)

dBA18 <- 
  d18 %>% 
  mutate(BA = (pi*(DBH/24)^2)) %>%
  group_by(TRT, COMPGAP) %>% 
  summarise(sumBA = sum(BA)) %>% 
  left_join(plotsize_13_18) %>% 
  mutate(BA18_AC = sumBA/SIZE18_AC)

d13_18BA <- 
  dBA13 %>% left_join(dBA18, by = c("COMPGAP" = "COMPGAP")) %>% 
  mutate(BA13_18 = (BA18_AC - BA13_AC)/(BA13_AC*5)*100) %>% 
  select(TRT.x, COMPGAP, SIZE13_AC.x, SIZE18_AC.x, BA13_AC, BA18_AC, BA13_18) %>% 
  left_join(treatments, by = c('TRT.x' = 'TRT'))
colnames(d13_18BA) <- (c("TRT", "COMPGAP", "SIZE13_AC", "SIZE18_AC", "BA13_AC", "BA18_AC", "BA13_18", "Treatment"))
d13_18BA
```

```{r}
BA_mean <- 
  d13_18BA %>% 
  group_by(Treatment) %>% 
  summarise(mean = mean(BA13_18))

ggplot(d13_18BA) + 
  geom_boxplot(aes(x = reorder(Treatment, BA13_18, FUN = median), y = BA13_18)) + 
  geom_point(data = BA_mean, aes(x = Treatment, y = mean), col = "red", pch = 4, size = 2) + 
  labs(x = 'Treatment', 
       y = 'Relativized basal area increment [%/yr]')
```

```{r}
SBA_lm <- lm(BA13_18 ~ TRT, d13_18BA)
plot(SBA_lm)

shapiro.test(residuals(SBA_lm))
car::leveneTest(BA13_18 ~ TRT, d13_18BA)

SBA_aov <- aov(data = d13_18BA, formula = BA13_18 ~ TRT)
summary(SBA_aov)
TukeyHSD(SBA_aov)
```

```{r}
plot(SBA_aov)

```


```{r}
BAeff <- as.data.frame(effect('TRT', SBA_aov)) %>% 
  left_join(treatments)

ggplot(BAeff) + 
  geom_pointrange(aes(x = reorder(Treatment, fit, FUN = mean), 
                      y = fit, 
                      ymin = lower, 
                      ymax = upper), 
                  fatten = 2.5) + 
  labs(x = 'Treatment', 
       y = 'Relativized basal area increment [%/yr]')
```



```{r}
ggplot(d20, aes(y = REPL, x = PER_DIFF)) + geom_point() + facet_grid(TRT ~ .) + xlim(-80, 130)

ggplot(d20_cln, aes(y = REPL, x = PER_DIFF)) + geom_point() + facet_grid(TRT ~ .) + xlim(-80, 130)


ggplot(d20, aes(y = REPL, x = PER_DIFF)) + geom_point() + facet_grid(SPP ~ .) + xlim(-80, 130)

ggplot(d20_cln, aes(y = REPL, x = PER_DIFF)) + geom_point() + facet_grid(SPP ~ .) + xlim(-80, 130)

```

```{r}
d20_naov <- lmerTest::lmer(PER_DIFF ~ Treatment*SPP + (1 | REPL/TRT), data = d20_noGS)

summary(d20_naov)
#summary(allFit(d20_naov))
```

```{r}
plot(d20_naov)

plot(fitted(d20_naov), residuals(d20_naov, type = "pearson",
    scaled = TRUE))

qqnorm(resid(d20_naov))
qqline(resid(d20_naov))
```

```{r}
library(sjPlot)
plot_model(d20_naov, type = "eff", terms = "Treatment", sort.est = TRUE) + 
  labs(y = 'Percent difference [%]', title = element_blank())

plot_model(d20_naov, type = "pred", terms = "Treatment", sort.est = TRUE) + 
  labs(y = 'Percent difference [%]', title = element_blank())
```

```{r}
naov_TRTSPPeff <- as.data.frame(effect('Treatment*SPP', d20_naov))

naov_TRTeff <- as.data.frame(effect("Treatment", d20_naov))

ggplot() + 
  geom_pointrange(data = naov_TRTeff,
                  aes(y = fit,
                      x = reorder(x = Treatment, X = -fit, FUN = mean),
                      ymin = lower,
                      ymax = upper),
                  fatten = 2.5) +
  geom_line(data = naov_TRTSPPeff, 
            aes(x = Treatment, 
                y = fit, 
                group = SPP, 
                colour = SPP)) + 
  # geom_ribbon(data = naov_TRTSPPeff, 
  #             aes(x = Treatment, 
  #                 y = fit, 
  #                 ymin = lower, 
  #                 ymax = upper, 
  #                 group = SPP, 
  #                 colour = SPP), 
  #             linetype = 2, 
  #             alpha = 0.1) + 
  labs(y = "Percent difference [%]",
       x = 'Treatment')
```

```{r}
naov_SPPeff <- as.data.frame(effect('SPP', d20_naov))

ggplot() + 
  geom_pointrange(data = naov_SPPeff,
                  aes(y = fit,
                      x = reorder(x = SPP, X = fit, FUN = mean),
                      ymin = lower,
                      ymax = upper, 
                      colour = SPP),
                  fatten = 2.5) +
  labs(y = "Percent difference [%]",
       x = 'Species') + 
  theme(legend.position = 'none')
```

```{r}
#plot(effect('Treatment*SPP', d20_naov))

naov_TRTSPPeff <- left_join(naov_TRTSPPeff, treatments)

ggplot(naov_TRTSPPeff) + 
  geom_point(aes(x = Treatment, 
                   y = fit,
                   group = SPP, 
                   colour = SPP)) + 
  geom_line(aes(x = Treatment, 
                y = fit, 
                group = SPP, 
                colour = SPP)) +
  theme(legend.position = 'none') + 
  labs(x = 'Treatment', 
       y = "Percent difference [%]")


ggplot(naov_TRTSPPeff) + 
  geom_pointrange(aes(x = TRT, 
                   y = fit, 
                   ymin = lower, 
                   ymax = upper, 
                   group = SPP, 
                   colour = SPP), 
                  fatten = 2.5) + 
  geom_line(aes(x = TRT, 
                y = fit, 
                group = SPP, 
                colour = SPP)) +
  facet_wrap(~SPP) + 
  theme(legend.position = 'none') + 
  labs(x = 'Treatment', 
       y = "Percent difference [%]")
```

```{r}
library(emmeans)

emmeans(d20_naov, list(pairwise ~ Treatment), adjust = 'tukey')

emmeans(d20_naov, list(pairwise ~ SPP), adjust = 'tukey')

emmeans(d20_naov, list(pairwise ~ Treatment | SPP), adjust = 'tukey')

emmip(d20_naov, SPP ~ Treatment) + labs(x = 'Treatment', y = 'Percent difference [%]')
```

